version: '3.1'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
    image:  woov/rabbitmq-delayed-message-exchange
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"