server:
  port: ${port:8081}

spring:
  main:
    banner-mode: "off"
  application:
    name: ${name:cr-sales-ms}
  profiles:
    active: ${profiles_active:local}
  data:
    mongodb:
      uri: ${database_mongodb_uri:mongodb://root:password@localhost:27017/sales?authSource=admin&maxIdleTimeMS=15000}
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

management:
  endpoint:
    health:
      show-details: "ALWAYS"

app:
  repository:
    maximumLimit: ${app_repository_maximumLimit:100}
    defaultLimit: ${app_repository_defaultLimit:10}

info:
  build:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
    date: '@timestamp@'